name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Print requirements.txt
      run: cat requirements.txt
        
    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt || { echo "Failed to install dependencies"; cat failed_install.log; exit 1; }
      env:
        PIP_NO_CACHE_DIR: off
      continue-on-error: true
      
    - name: Upload failed install log
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: failed-install-log
        path: failed_install.log
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ml-model-flask-api:latest
